/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v14.0
processor: MIMXRT595S
package_id: MIMXRT595SFFOC
mcu_data: ksdk2_0
processor_version: 14.0.0
board: MIMXRT595-EVK
pin_labels:
- {pin_num: B12, pin_signal: PIO0_14/FC2_SCK/SCT0_GPI0/SCT0_OUT0/CTIMER2_MAT0/I2S_BRIDGE_CLK_IN/SEC_PIO0_14, label: 'Q3[2]/PWM_RED_LED', identifier: LED_RED}
- {pin_num: A10, pin_signal: PIO1_0/FC4_RTS_SCL_SSEL1/SCT0_GPI1/SCT0_OUT7/CTIMER_INP8/FC3_SSEL3, label: 'Q4[5]/PWM_GRN_LED', identifier: LED_GREEN}
- {pin_num: D12, pin_signal: PIO0_31/FC4_CTS_SDA_SSEL0/SCT0_GPI0/SCT0_OUT6/CTIMER4_MAT3/FC3_SSEL2/SEC_PIO0_31, label: WL_REG_ON}
- {pin_num: L6, pin_signal: VSS30, label: GND}
- {pin_num: C7, pin_signal: VSS5, label: GND}
- {pin_num: D7, pin_signal: VSSA1, label: GND}
- {pin_num: E7, pin_signal: VSS7, label: GND}
- {pin_num: G7, pin_signal: VSS16, label: GND}
- {pin_num: A1, pin_signal: VSS0, label: GND}
- {pin_num: U1, pin_signal: VSS42, label: GND}
- {pin_num: C3, pin_signal: VSS4, label: GND}
- {pin_num: G3, pin_signal: VSS13, label: GND}
- {pin_num: L3, pin_signal: VSS27, label: GND}
- {pin_num: R3, pin_signal: VSS40, label: GND}
- {pin_num: G4, pin_signal: VSS14, label: GND}
- {pin_num: F4, pin_signal: MIPI_DSI_VSS, label: GND}
- {pin_num: L4, pin_signal: VSS28, label: GND}
- {pin_num: G5, pin_signal: VSS15, label: GND}
- {pin_num: L5, pin_signal: VSS29, label: GND}
- {pin_num: K7, pin_signal: VSS20, label: GND}
- {pin_num: L7, pin_signal: VSS31, label: GND}
- {pin_num: M7, pin_signal: VSS34, label: GND}
- {pin_num: N7, pin_signal: VSS36, label: GND}
- {pin_num: R7, pin_signal: VSS41, label: GND}
- {pin_num: G8, pin_signal: VSS17, label: GND}
- {pin_num: L8, pin_signal: VSS32, label: GND}
- {pin_num: G10, pin_signal: VSS8, label: GND}
- {pin_num: L10, pin_signal: VSS21, label: GND}
- {pin_num: C11, pin_signal: VSS2, label: GND}
- {pin_num: D11, pin_signal: VSSA0, label: GND}
- {pin_num: E11, pin_signal: VSS6, label: GND}
- {pin_num: G11, pin_signal: VSS9, label: GND}
- {pin_num: H11, pin_signal: VSS18, label: GND}
- {pin_num: K11, pin_signal: VSS19, label: GND}
- {pin_num: L11, pin_signal: VSS22, label: GND}
- {pin_num: M11, pin_signal: VSS33, label: GND}
- {pin_num: N11, pin_signal: VSS35, label: GND}
- {pin_num: P11, pin_signal: VSS37, label: GND}
- {pin_num: R11, pin_signal: VSS38, label: GND}
- {pin_num: L12, pin_signal: VSS23, label: GND}
- {pin_num: G13, pin_signal: VSS10, label: GND}
- {pin_num: L13, pin_signal: VSS24, label: GND}
- {pin_num: G14, pin_signal: VSS11, label: GND}
- {pin_num: L14, pin_signal: VSS25, label: GND}
- {pin_num: C15, pin_signal: VSS3, label: GND}
- {pin_num: G15, pin_signal: VSS12, label: GND}
- {pin_num: L15, pin_signal: VSS26, label: GND}
- {pin_num: R15, pin_signal: VSS39, label: GND}
- {pin_num: A17, pin_signal: VSS1, label: GND}
- {pin_num: U17, pin_signal: VSS43, label: GND}
- {pin_num: H8, pin_signal: VDDCORE2, label: MCU_VDDCORE}
- {pin_num: K8, pin_signal: VDDCORE8, label: MCU_VDDCORE}
- {pin_num: G9, pin_signal: VDDCORE0, label: MCU_VDDCORE}
- {pin_num: H9, pin_signal: VDDCORE3, label: MCU_VDDCORE}
- {pin_num: J9, pin_signal: VDDCORE6, label: MCU_VDDCORE}
- {pin_num: K9, pin_signal: VDDCORE9, label: MCU_VDDCORE}
- {pin_num: L9, pin_signal: VDDCORE10, label: MCU_VDDCORE}
- {pin_num: H10, pin_signal: VDDCORE1, label: MCU_VDDCORE}
- {pin_num: J10, pin_signal: VDDCORE4, label: MCU_VDDCORE}
- {pin_num: K10, pin_signal: VDDCORE7, label: MCU_VDDCORE}
- {pin_num: J11, pin_signal: VDDCORE5, label: MCU_VDDCORE}
- {pin_num: E12, pin_signal: VDDA_BIAS, label: MCU_3V3}
- {pin_num: H13, pin_signal: VDDA_ADC1V8, label: MCU_1V8}
- {pin_num: B2, pin_signal: VDD_AO1V81, label: MCU_AO1V8}
- {pin_num: D4, pin_signal: VDD_AO1V80, label: MCU_AO1V8}
- {pin_num: J5, pin_signal: VDDIO_14, label: MCU_VDDIO_1}
- {pin_num: J6, pin_signal: VDDIO_15, label: MCU_VDDIO_1}
- {pin_num: E9, pin_signal: VDDIO_10, label: MCU_VDDIO_1}
- {pin_num: F9, pin_signal: VDDIO_13, label: MCU_VDDIO_1}
- {pin_num: F10, pin_signal: VDDIO_11, label: MCU_VDDIO_1}
- {pin_num: F11, pin_signal: VDDIO_12, label: MCU_VDDIO_1}
- {pin_num: M10, pin_signal: VDDIO_03, label: MCU_VDDIO_0}
- {pin_num: J12, pin_signal: VDDIO_00, label: MCU_VDDIO_0}
- {pin_num: K12, pin_signal: VDDIO_02, label: MCU_VDDIO_0}
- {pin_num: M12, pin_signal: VDDIO_04, label: MCU_VDDIO_0}
- {pin_num: J13, pin_signal: VDDIO_01, label: MCU_VDDIO_0}
- {pin_num: N6, pin_signal: VDDIO_20, label: MCU_VDDIO_2}
- {pin_num: P7, pin_signal: VDDIO_21, label: MCU_VDDIO_2}
- {pin_num: M8, pin_signal: VDDIO_30, label: MCU_VDDIO_3}
- {pin_num: N9, pin_signal: VDDIO_31, label: MCU_VDDIO_3}
- {pin_num: F6, pin_signal: VDDIO_40, label: MCU_VDDIO_4}
- {pin_num: F7, pin_signal: VDDIO_41, label: MCU_VDDIO_4}
- {pin_num: E6, pin_signal: VDD_PLL18, label: MCU_1V8}
- {pin_num: H6, pin_signal: VDD1V82, label: MCU_1V8}
- {pin_num: M6, pin_signal: VDD1V80, label: MCU_1V8}
- {pin_num: J14, pin_signal: VDD1V81, label: MCU_1V8}
- {pin_num: E8, pin_signal: VDD1V8_1, label: MCU_1V8}
- {pin_num: F5, pin_signal: MIPI_DSI_VDDA_CAP, label: MIPI_VDDA}
- {pin_num: F8, pin_signal: MIPI_DSI_VDD18, label: MCU_1V8}
- {pin_num: J8, pin_signal: MIPI_DSI_VDD11, label: 'JS25[1]/MCU_VDDCORE'}
- {pin_num: K5, pin_signal: USB1_VDD3V3, label: MCU_3V3}
- {pin_num: K16, pin_signal: PIO0_10/FC1_CTS_SDA_SSEL0/SCT0_GPI7/SCT0_OUT7/CTIMER1_MAT3/FC0_SSEL2/SEC_PIO0_10, label: USER_KEY2, identifier: SW2}
- {pin_num: C12, pin_signal: PIO0_25/FC3_RTS_SCL_SSEL1/FREQME_GPIO_CLK/CTIMER_INP6/FC2_SSEL3/TRACEDATA_3/CLKIN/SEC_PIO0_25, label: USER_KEY1, identifier: SW1}
- {pin_num: G16, pin_signal: PIO0_1/FC0_TXD_SCL_MISO_WS/CTIMER0_MAT1/I2S_BRIDGE_WS_IN/SEC_PIO0_1, label: 'J45[32]/U105[3]/U9[12]', identifier: DEBUG_UART_TXD}
- {pin_num: H16, pin_signal: PIO0_2/FC0_RXD_SDA_MOSI_DATA/CTIMER0_MAT2/I2S_BRIDGE_DATA_IN/SEC_PIO0_2, label: 'J45[22]/U9[13]/U105[4]', identifier: DEBUG_UART_RX}
- {pin_num: F12, pin_signal: VREFP, label: MCU_1V8}
- {pin_num: G12, pin_signal: VREFN, label: GND}
- {pin_num: C4, pin_signal: RESETN, label: 'JP14[2]', identifier: nRESET_TRGT}
- {pin_num: D1, pin_signal: MIPI_DSI_CLKN, label: 'J44[11]', identifier: MIPI_TCN}
- {pin_num: D2, pin_signal: MIPI_DSI_CLKP, label: 'J44[12]', identifier: MIPI_TCP}
- {pin_num: B1, pin_signal: MIPI_DSI_D0P, label: 'J44[6]', identifier: MIPI_TDP0}
- {pin_num: C2, pin_signal: MIPI_DSI_D0N, label: 'J44[5]', identifier: MIPI_TDN0}
- {pin_num: E3, pin_signal: MIPI_DSI_D1P, label: 'J44[9]', identifier: MIPI_TDP1}
- {pin_num: F3, pin_signal: MIPI_DSI_D1N, label: 'J44[8]', identifier: MIPI_TDN1}
- {pin_num: K4, pin_signal: PMIC_I2C_SCL, label: 'U30[D5]', identifier: PMIC_I2C_SCL}
- {pin_num: K6, pin_signal: PMIC_I2C_SDA, label: 'U30[E5]', identifier: PMIC_I2C_SDA}
- {pin_num: E4, pin_signal: PMIC_MODE1, label: 'U30[E3]'}
- {pin_num: D3, pin_signal: PMIC_MODE0, label: 'U30[E4]'}
- {pin_num: D5, pin_signal: PMIC_IRQ_N, label: 'U30[D4]'}
- {pin_num: C5, pin_signal: LDO_ENABLE, label: 'JS28[2]'}
- {pin_num: A2, pin_signal: RTCXIN, label: 'Y5[1]'}
- {pin_num: B3, pin_signal: RTCXOUT, label: 'Y5[2]'}
- {pin_num: T1, pin_signal: USB1_DM, label: 'J38[2]/RT_USB1_DM'}
- {pin_num: U2, pin_signal: USB1_DP, label: 'J38[3]/RT_USB1_DP'}
- {pin_num: T2, pin_signal: USB1_VBUS, label: USB_HS_VBUS_TRGT}
- {pin_num: A4, pin_signal: XTALOUT, label: 'Y2[3]'}
- {pin_num: B4, pin_signal: XTALIN, label: 'Y2[1]'}
- {pin_num: M3, pin_signal: PIO2_27/USB1_OVERCURRENTN/SMARTDMA_PIO27, label: 'U34[A2]/USB1_OC'}
- {pin_num: P1, pin_signal: PIO2_28/USB1_PORTPWRN/SMARTDMA_PIO28, label: 'U34[A1]/Q9[1]/USB1_PWR_EN'}
- {pin_num: F14, pin_signal: PIO0_0/FC0_SCK/CTIMER0_MAT0/I2S_BRIDGE_CLK_IN/GPIO_INT_BMAT/SEC_PIO0_0, label: 'JP6[2]'}
- {pin_num: C13, pin_signal: PIO0_23/FC3_RXD_SDA_MOSI_DATA/SCT0_GPI7/SCT0_OUT8/CTIMER3_MAT2/CTIMER0_MAT3/TRACEDATA_1/SEC_PIO0_23, label: 'JP7[2]/J19[16]'}
- {pin_num: H17, pin_signal: PIO0_9/FC1_RXD_SDA_MOSI_DATA/SCT0_GPI6/SCT0_OUT6/CTIMER1_MAT2/I2S_BRIDGE_DATA_OUT/SEC_PIO0_9, label: 'JP8[2]'}
- {pin_num: H12, pin_signal: PIO0_8/FC1_TXD_SCL_MISO_WS/SCT0_GPI5/SCT0_OUT5/CTIMER1_MAT1/I2S_BRIDGE_WS_OUT/SEC_PIO0_8, label: 'JP28[2]'}
- {pin_num: J15, pin_signal: PIO0_7/FC1_SCK/SCT0_GPI4/SCT0_OUT4/CTIMER1_MAT0/I2S_BRIDGE_CLK_OUT/SEC_PIO0_7, label: 'JP29[2]'}
- {pin_num: M16, pin_signal: PIO1_15/HS_SPI0_SSELN1/CTIMER3_MAT0, label: 'SW7-6/JP13[3]/ISP0'}
- {pin_num: K13, pin_signal: PIO1_11/HS_SPI0_SCK/CTIMER2_MAT0, label: 'J36[7]/U4[B2]', identifier: SPI_CLK}
- {pin_num: K14, pin_signal: PIO1_12/HS_SPI0_MISO/CTIMER2_MAT1, label: 'J36[5]', identifier: SPI_MISO}
- {pin_num: K17, pin_signal: PIO1_13/HS_SPI0_MOSI/CTIMER2_MAT2, label: 'J36[3]/U4[B4]', identifier: SPI_MOSI}
- {pin_num: L16, pin_signal: PIO1_14/HS_SPI0_SSELN0/CTIMER2_MAT3, label: 'J36[1]/U4[B1]', identifier: SPI_SS0}
- {pin_num: H15, pin_signal: PIO0_3/FC0_CTS_SDA_SSEL0/CTIMER0_MAT3/FC1_SSEL2/SEC_PIO0_3, label: 'J45[34]/J36[4]/U105[6]/FC0_CTS'}
- {pin_num: H14, pin_signal: PIO0_4/FC0_RTS_SCL_SSEL1/CTIMER_INP0/FC1_SSEL3/CMP0_OUT/SEC_PIO0_4, label: 'J45[36]/U105[5]/FC0_RTS'}
- {pin_num: N13, pin_signal: PIO3_28/FC6_CTS_SDA_SSEL0, label: 'JP13[1]/SW7-5/ISP1'}
- {pin_num: M13, pin_signal: PIO3_29/FC6_RTS_SCL_SSEL1, label: SW7-4/ISP2}
- {pin_num: H1, pin_signal: PIO4_12/FC2_TXD_SCL_MISO_WS/FLEXSPI1_DATA0/SD1_CMD, label: 'U108[D3]', identifier: PSRAM_ADQ0}
- {pin_num: F1, pin_signal: PIO4_14/FC2_CTS_SDA_SSEL0/FLEXSPI1_DATA2/SD1_D1, label: 'U108[C4]', identifier: PSRAM_ADQ2}
- {pin_num: G2, pin_signal: PIO4_13/FC2_RXD_SDA_MOSI_DATA/FLEXSPI1_DATA1/SD1_D0, label: 'U108[D2]', identifier: PSRAM_ADQ1}
- {pin_num: H2, pin_signal: PIO4_11/FC2_SCK/FLEXSPI1_SCLK/SD1_CLK, label: 'U108[B2]', identifier: PSRAM_CLK}
- {pin_num: H3, pin_signal: PIO4_16/FC2_SSEL2/FLEXSPI1_DQS/SD1_D3, label: 'U108[C3]', identifier: PSRAM_DQS}
- {pin_num: K3, pin_signal: PIO4_15/FC2_RTS_SCL_SSEL1/FLEXSPI1_DATA3/SD1_D2, label: 'U108[D4]', identifier: PSRAM_ADQ3}
- {pin_num: E13, pin_signal: PIO4_18/FLEXSPI1_SS0_N/SD1_D4/ADC0_6, label: 'U108[A3]', identifier: PSRAM_CE}
- {pin_num: J3, pin_signal: PIO5_17/LCD_D22/FLEXSPI1_DATA6/FC4_SSEL2, label: 'U108[E2]', identifier: PSRAM_ADQ6}
- {pin_num: H4, pin_signal: PIO5_16/LCD_D21/FLEXSPI1_DATA5/FC4_RTS_SCL_SSEL1, label: 'U108[E3]', identifier: PSRAM_ADQ5}
- {pin_num: J4, pin_signal: PIO5_18/LCD_D23/FLEXSPI1_DATA7/FC4_SSEL3, label: 'U108[E1]', identifier: PSRAM_ADQ7}
- {pin_num: H5, pin_signal: PIO5_15/LCD_D20/FLEXSPI1_DATA4/FC4_CTS_SDA_SSEL0, label: 'U108[D5]', identifier: PSRAM_ADQ4}
- {pin_num: F2, pin_signal: PIO4_17/FC2_SSEL3/FLEXSPI1_SS1_N/FLEXSPI1_SCLK_N/SD1_WR_PRT, label: FLEXSPI1_SCLK_N}
- {pin_num: N12, pin_signal: PIO1_24/FLEXSPI0_DATA4/SCT0_GPI3, label: 'U38[D5]', identifier: FLEXSPI0_DATA4}
- {pin_num: R12, pin_signal: PIO1_23/FLEXSPI0_DATA3/SCT0_OUT2/CTIMER_INP8, label: 'U38[D4]', identifier: FLEXSPI0_DATA3}
- {pin_num: P13, pin_signal: PIO1_27/FLEXSPI0_DATA7/SCT0_OUT4, label: 'U38[E1]', identifier: FLEXSPI0_DATA7}
- {pin_num: R13, pin_signal: PIO1_22/FLEXSPI0_DATA2/SCT0_GPI2/CTIMER4_MAT3, label: 'U38[C4]', identifier: FLEXSPI0_DATA2}
- {pin_num: P14, pin_signal: PIO1_26/FLEXSPI0_DATA6/SCT0_GPI4, label: 'U38[E2]', identifier: FLEXSPI0_DATA6}
- {pin_num: R14, pin_signal: PIO1_25/FLEXSPI0_DATA5/SCT0_OUT3, label: 'U38[E3]', identifier: FLEXSPI0_DATA5}
- {pin_num: T14, pin_signal: PIO1_21/FLEXSPI0_DATA1/SCT0_OUT1/CTIMER4_MAT2, label: 'U38[D2]', identifier: FLEXSPI0_DATA1}
- {pin_num: U14, pin_signal: PIO1_28/FLEXSPI0_DQS/SCT0_GPI5, label: 'U38[C3]', identifier: FLEXSPI0_DQS}
- {pin_num: T15, pin_signal: PIO1_20/FLEXSPI0_DATA0/SCT0_GPI1/CTIMER4_MAT1, label: 'U38[D3]', identifier: FLEXSPI0_DATA0}
- {pin_num: U16, pin_signal: PIO1_19/FLEXSPI0_SS0_N/SCT0_OUT0/CTIMER4_MAT0/CLKOUT, label: 'U38[C2]', identifier: FLEXSPI0_CS}
- {pin_num: T17, pin_signal: PIO1_18/FLEXSPI0_SCLK/SCT0_GPI0/CTIMER3_MAT3, label: 'U38[B2]', identifier: FLEXSPI0_SCLK}
- {pin_num: M4, pin_signal: PIO2_26/SWDIO/SMARTDMA_PIO26, label: 'J19[2]/J2[2]/SWDIO', identifier: SWDIO}
- {pin_num: M2, pin_signal: PIO2_25/SWCLK/SMARTDMA_PIO25, label: 'U7[4]', identifier: SWDCLK}
- {pin_num: N3, pin_signal: PIO2_24/SWO/GPIO_INT_BMAT/SMARTDMA_PIO24, label: 'U7[12]', identifier: SWO}
- {pin_num: R8, pin_signal: PIO4_20/DBI_CSX/SD1_D6/FC11_SCK/FLEXIO_D0, label: 'J27[3]/J43[13]', identifier: FXIO_D0}
- {pin_num: P10, pin_signal: PIO4_21/DBI_DSX/SD1_D7/FC11_TXD_SCL_MISO/FLEXIO_D1, label: 'J28[10]/J30[6]/J43[14]/FXIO_D1', identifier: D1}
- {pin_num: U10, pin_signal: PIO4_22/SD1_CARD_DET_N/FC11_RXD_SDA_MOSI/FLEXIO_D2, label: 'J28[9]/J30[5]/J43[15]/FXIO_D2', identifier: D2}
- {pin_num: T8, pin_signal: PIO4_23/DBI_RWDX/LCD_ENABLE/SD1_RESET_N/FC11_CTS_SDA_SSELN0/TRACECLK/FLEXIO_D3, label: 'J27[4]/J43[16]/FXIO_D3', identifier: D3}
- {pin_num: T10, pin_signal: PIO4_24/DBI_WRX/LCD_DTCLK/SD1_VOLT/FC11_RTS_SCL_SSELN1/TRACEDATA_0/FLEXIO_D4, label: 'J27[5]/J43[17]/FXIO_D4', identifier: D4}
- {pin_num: T11, pin_signal: PIO4_25/DBI_E/LCD_HSYNC/FC11_SSELN2/TRACEDATA_1/FLEXIO_D5, label: 'J27[6]/J43[18]/FXIO_D5', identifier: D5}
- {pin_num: T12, pin_signal: PIO4_26/LCD_VSYNC/FC11_SSELN3/TRACEDATA_2/FLEXIO_D6, label: 'J27[7]/J43[19]/FXIO_D6', identifier: D6}
- {pin_num: P9, pin_signal: PIO4_27/LCD_D0/DBI_D0/TRACEDATA_3/FLEXIO_D7, label: 'J27[8]/J43[20]/FXIO_D7', identifier: D7}
- {pin_num: U8, pin_signal: PIO4_28/LCD_D1/DBI_D1/FLEXIO_D8, label: 'J28[1]/J43[6]/FXIO_D8', identifier: D8}
- {pin_num: P8, pin_signal: PIO4_29/LCD_D2/DBI_D2/FLEXIO_D9, label: 'J28[2]/J43[12]/FXIO_D9', identifier: D9}
- {pin_num: N8, pin_signal: PIO4_30/LCD_D3/DBI_D3/FC12_TXD_SCL_MISO/FLEXIO_D10, label: 'J27[2]/J43[5]/FXIO_D10', identifier: D10}
- {pin_num: N10, pin_signal: PIO4_31/LCD_D4/DBI_D4/FC12_RXD_SDA_MOSI/FLEXIO_D11, label: 'J27[1]/J43[8]/FXIO_D11', identifier: D11}
- {pin_num: B10, pin_signal: PIO2_29/I3C0_SCL/SCT0_OUT0/CLKOUT/SMARTDMA_PIO29, label: 'J18[1]/U8[2]/U114[A1]', identifier: I3C0_SCL}
- {pin_num: D10, pin_signal: PIO2_30/I3C0_SDA/SCT0_OUT3/CLKIN/CMP0_OUT/SMARTDMA_PIO30, label: 'J18[2]/U8[3]/U114[A2]', identifier: I3C0_SDA}
- {pin_num: C14, pin_signal: PIO2_31/I3C0_PUR/SCT0_OUT7/UTICK_CAP3/CTIMER_INP15/SWO/SMARTDMA_PIO31/CMP0_B, label: 'J18[3]', identifier: I3C0_PUR}
- {pin_num: P2, pin_signal: PIO5_4/LCD_D9/DBI_D9/PDM_CLK01, label: 'J31[3]/J31[5]/J31[7]/J31[9]', identifier: DMIC_PDM_CLK01}
- {pin_num: P3, pin_signal: PIO5_8/LCD_D13/DBI_D13/PDM_DATA01, label: 'J31[4]', identifier: DMIC_PDM_DAT01}
- {pin_num: D16, pin_signal: PIO3_1/PDM_CLK23/PDM_DATA23/FC0_TXD_SCL_MISO_WS/I3C1_SCL, label: 'J31[6]', identifier: DMIC_PDM_DAT23}
- {pin_num: C16, pin_signal: PIO3_2/PDM_CLK45/PDM_DATA45/FC0_RXD_SDA_MOSI_DATA/I3C1_SDA, label: 'J31[8]', identifier: DMIC_PDM_DAT45}
- {pin_num: D15, pin_signal: PIO3_3/PDM_CLK67/PDM_DATA67/LCD_D23/FC0_CTS_SDA_SSEL0/I3C1_PUR/CMP0_OUT, label: 'J31[10]', identifier: DMIC_PDM_DAT67}
- {pin_num: N5, pin_signal: PIO2_10/SD0_RESET_N/SCT0_GPI6/CTIMER2_MAT0/FC8_SSEL2/SMARTDMA_PIO10, label: SD0_RESET_N, identifier: SD0_RESET_N}
- {pin_num: R5, pin_signal: PIO1_30/SD0_CLK/SCT0_GPI0, label: 'U111A[M6]/SD0_CLK', identifier: SD0_CLK}
- {pin_num: R6, pin_signal: PIO1_31/SD0_CMD/SCT0_GPI1, label: 'U111A[M5]/SD0_CMD', identifier: SD0_CMD}
- {pin_num: U4, pin_signal: PIO2_0/SD0_D0/SCT0_GPI2/SMARTDMA_PIO0, label: 'U111A[A3]/SD0_D0', identifier: SD0_D0}
- {pin_num: T4, pin_signal: PIO2_1/SD0_D1/SCT0_GPI3/SMARTDMA_PIO1, label: 'U111A[A4]/SD0_D1', identifier: SD0_D1}
- {pin_num: T7, pin_signal: PIO2_2/SD0_D2/SCT0_OUT0/SMARTDMA_PIO2, label: 'U111A[A5]/SD0_D2', identifier: SD0_D2}
- {pin_num: U6, pin_signal: PIO2_3/SD0_D3/SCT0_OUT1/SMARTDMA_PIO3, label: 'U111A[B2]/SD0_D3', identifier: SD0_D3}
- {pin_num: T3, pin_signal: PIO2_9/SD0_CARD_DET_N/SCT0_OUT5/CTIMER1_MAT3/FC8_CTS_SDA_SSEL1/SMARTDMA_PIO9, label: 'J32[10]/SD0_CARD_DET_N', identifier: SD0_CARD_DET_N}
- {pin_num: P6, pin_signal: PIO2_4/SD0_WR_PRT/SCT0_OUT2/SD0_DS/SMARTDMA_PIO4, label: 'U111A[H5]/SD0_WR_PRT_DS', identifier: SD0_WR_PRT_DS}
- {pin_num: P5, pin_signal: PIO2_5/SD0_D4/SCT0_OUT3/FC8_SCK/SMARTDMA_PIO5, label: 'U111A[B3]/SD0_D4', identifier: SD0_D4}
- {pin_num: R4, pin_signal: PIO2_6/SD0_D5/SCT0_GPI4/CTIMER1_MAT0/FC8_TXD_SCL_MISO_WS/SMARTDMA_PIO6, label: 'U111A[B4]/SD0_D5', identifier: SD0_D5}
- {pin_num: P4, pin_signal: PIO2_7/SD0_D6/SCT0_GPI5/CTIMER1_MAT1/FC8_RXD_SDA_MOSI_DATA/SMARTDMA_PIO7, label: 'U111A[B5]/SD0_D6', identifier: SD0_D6}
- {pin_num: T6, pin_signal: PIO2_8/SD0_D7/SCT0_OUT4/CTIMER1_MAT2/FC8_CTS_SDA_SSEL0/SMARTDMA_PIO8, label: 'U111A[B6]/SD0_D7', identifier: SD0_D7}
- {pin_num: R2, pin_signal: PIO2_11/SD0_VOLT/SCT0_GPI7/CTIMER2_MAT1/FC8_SSEL3/SMARTDMA_PIO11, label: 'J38[4]/RT_USB1_ID'}
- {pin_num: C9, pin_signal: PIO3_16/SD1_D5/LCD_D17/CTIMER3_MAT2/FC5_TXD_SCL_MISO_WS, label: BT_REG_ON}
- {pin_num: D8, pin_signal: PIO3_17/SD1_D6/LCD_D18/CTIMER3_MAT3/FC5_RXD_SDA_MOSI_DATA, label: 'Q4[2]/PWM_BLU_LED', identifier: LED_BLUE}
- {pin_num: B14, pin_signal: PIO0_22/FC3_TXD_SCL_MISO_WS/SCT0_GPI6/SCT0_OUT6/CTIMER3_MAT1/CTIMER_INP7/TRACEDATA_0/SEC_PIO0_22, label: 'J19[14]/U6[11]/ACC_INT', identifier: ACC_INT}
- {pin_num: M1, pin_signal: PIO1_7/FC5_RTS_SCL_SSEL1/SCT0_GPI5/SCT0_OUT5/CTIMER_INP9/FC4_SSEL3/HS_SPI1_SSELN1, label: 'U6[16]/ACC_RESET', identifier: ACC_RESET}
- {pin_num: K2, pin_signal: PIO1_3/FC5_SCK/HS_SPI1_SCK, label: 'JP26[4]', identifier: SPI_CLK}
- {pin_num: L2, pin_signal: PIO1_5/FC5_RXD_SDA_MOSI_DATA/HS_SPI1_MOSI, label: 'JP26[2]', identifier: SPI_MOSI}
- {pin_num: N4, pin_signal: PIO1_6/FC5_CTS_SDA_SSEL0/SCT0_GPI4/SCT0_OUT4/FC4_SSEL2/HS_SPI1_SSELN0, label: 'JP26[1]', identifier: SPI_SS0}
- {pin_num: K1, pin_signal: PIO1_4/FC5_TXD_SCL_MISO_WS/HS_SPI1_MISO, label: 'JP26[3]/U4[B3]', identifier: SPI_MISO}
- {pin_num: M5, pin_signal: PIO1_10/MCLK/FREQME_GPIO_CLK/CTIMER_INP10/CLKOUT, label: 'JP27[2]', identifier: MCLK}
- {pin_num: U12, pin_signal: PIO1_29/FLEXSPI0_SS1_N/SCT0_OUT5/UTICK_CAP2/CTIMER_INP13/FLEXSPI0_SCLK_N, label: NC}
- {pin_num: E10, pin_signal: PIO3_15/SD1_D4/LCD_D16/CTIMER3_MAT1/FC5_SCK, label: 'U44[4]/LCM_PWR_EN', identifier: LCM_PWR_EN}
- {pin_num: E5, pin_signal: PIO3_21/SD1_VOLT/LCD_D22/CTIMER4_MAT3/GPIO_INT_BMAT, label: 'J44[21]/LCM_RESET_B', identifier: LCM_RESET_B}
- {pin_num: D17, pin_signal: PIO2_15/SCT0_OUT9/CLKIN/SMARTDMA_PIO15/CMP0_D, label: 'J47[10]/CMP0_D'}
- {pin_num: F16, pin_signal: PIO0_5/FC0_SSEL2/SCT0_GPI0/SCT0_OUT0/CTIMER_INP1/SEC_PIO0_5/ADC0_0, label: 'J30[1]'}
- {pin_num: F17, pin_signal: PIO0_6/FC0_SSEL3/SCT0_GPI1/SCT0_OUT1/CTIMER0_MAT0/SEC_PIO0_6/ADC0_8, label: 'J30[2]'}
- {pin_num: K15, pin_signal: PIO0_11/FC1_RTS_SCL_SSEL1/SCT0_GPI0/SCT0_OUT8/CTIMER_INP2/FC0_SSEL3/SEC_PIO0_11, label: 'J47[8]'}
- {pin_num: E14, pin_signal: PIO0_12/FC1_SSEL2/SCT0_GPI2/SCT0_OUT2/CTIMER_INP3/SEC_PIO0_12/ADC0_1, label: 'U44[5]/LCM_BL_PWM_1V8', identifier: LCM_BL_PWM}
- {pin_num: F15, pin_signal: PIO0_13/FC1_SSEL3/SCT0_GPI3/SCT0_OUT3/CTIMER0_MAT1/SEC_PIO0_13/ADC0_9, label: 'J30[4]'}
- {pin_num: B15, pin_signal: PIO0_15/FC2_TXD_SCL_MISO_WS/SCT0_GPI1/SCT0_OUT1/CTIMER2_MAT1/I2S_BRIDGE_WS_IN/SEC_PIO0_15, label: 'J36[6]/JS6[2]'}
- {pin_num: A16, pin_signal: PIO0_16/FC2_RXD_SDA_MOSI_DATA/SCT0_GPI2/SCT0_OUT2/CTIMER2_MAT2/I2S_BRIDGE_DATA_IN/SEC_PIO0_16, label: 'J36[8]/JS5[2]'}
- {pin_num: B17, pin_signal: PIO0_17/FC2_CTS_SDA_SSEL0/SCT0_GPI3/SCT0_OUT3/CTIMER2_MAT3/FC5_SSEL2/SEC_PIO0_17, label: 'J45[20]/M2_UART_WK_B'}
- {pin_num: B16, pin_signal: PIO0_18/FC2_RTS_SCL_SSEL1/SCT0_GPI6/SCT0_OUT6/CTIMER_INP4/FC5_SSEL3/SEC_PIO0_18, label: 'J45[21]/M2_SD1_WK_B'}
- {pin_num: F13, pin_signal: PIO0_19/FC2_SSEL2/SCT0_GPI4/SCT0_OUT4/CTIMER_INP5/UTICK_CAP0/SEC_PIO0_19/ADC0_2, label: 'J30[3]'}
- {pin_num: A14, pin_signal: PIO0_21/FC3_SCK/SCT0_GPI5/SCT0_OUT5/CTIMER3_MAT0/CTIMER_INP11/TRACECLK/SEC_PIO0_21, label: 'J19[12]'}
- {pin_num: P12, pin_signal: PIO5_0/LCD_D5/DBI_D5/FC12_CTS_SDA_SSELN0/FLEXIO_D12, label: 'J28[3]/J43[7]/FXIO_D12', identifier: RST}
- {pin_num: M9, pin_signal: PIO5_1/LCD_D6/DBI_D6/FC12_RTS_SCL_SSELN1/FLEXIO_D13, label: 'J28[4]/J43[9]/FXIO_D13', identifier: CS}
- {pin_num: R9, pin_signal: PIO5_2/LCD_D7/DBI_D7/FC12_SSELN2/LOW_FREQ_CLKOUT/FLEXIO_D14, label: 'J28[5]/J43[10]/FXIO_D14', identifier: WR}
- {pin_num: R10, pin_signal: PIO5_3/LCD_D8/DBI_D8/FC12_SSELN3/LOW_FREQ_CLKOUT_N/FLEXIO_D15, label: 'J28[6]/J43[11]/FXIO_D15', identifier: RD}
- {pin_num: D13, pin_signal: PIO0_24/FC3_CTS_SDA_SSEL0/SCT0_GPI2/SCT0_OUT9/CTIMER3_MAT3/FC2_SSEL2/TRACEDATA_2/CLKOUT/SEC_PIO0_24, label: 'J19[18]'}
- {pin_num: A12, pin_signal: PIO0_28/FC4_SCK/CTIMER4_MAT0/I2S_BRIDGE_CLK_OUT/SEC_PIO0_28, label: 'U108[A4]', identifier: PSRAM_RESET}
- {pin_num: B11, pin_signal: PIO0_29/FC4_TXD_SCL_MISO_WS/CTIMER4_MAT1/I2S_BRIDGE_WS_OUT/SEC_PIO0_29, label: 'J45[60]/I2C_SCL/U6[4]/ACC_I2C_SCL', identifier: ACC_I2C_SCL}
- {pin_num: D14, pin_signal: PIO0_30/FC4_RXD_SDA_MOSI_DATA/CTIMER4_MAT2/I2S_BRIDGE_DATA_OUT/SEC_PIO0_30, label: 'J45[58]/I2C_SDA/U6[6]/ACC_I2C_SDA', identifier: ACC_I2C_SDA}
- {pin_num: E15, pin_signal: PIO2_14/SCT0_OUT8/CTIMER_INP1/32KHZ_CLKOUT/SMARTDMA_PIO14/CMP0_A, label: 'Q17[1]'}
- {pin_num: A8, pin_signal: PIO3_8/SD1_CLK/LCD_D9/CTIMER0_MAT0/FC10_SCK, label: 'J45[9]/M2_SD1_CLK'}
- {pin_num: B8, pin_signal: PIO3_9/SD1_CMD/LCD_D10/CTIMER0_MAT1/FC10_TXD_SCL_MISO, label: 'J45[11]/M2_SD1_CMD'}
- {pin_num: C8, pin_signal: PIO3_10/SD1_D0/LCD_D11/CTIMER0_MAT2/FC10_RXD_SDA_MOSI, label: 'J45[13]/M2_SD1_DATA0'}
- {pin_num: C10, pin_signal: PIO3_11/SD1_D1/LCD_D12/CTIMER0_MAT3/FC10_CTS_SDA_SSELN0, label: 'J45[15]/M2_SD1_DATA1'}
- {pin_num: A6, pin_signal: PIO3_12/SD1_D2/LCD_D13/CTIMER_INP0/FC10_RTS_SCL_SSELN1, label: 'J45[17]/M2_SD1_DATA2'}
- {pin_num: B7, pin_signal: PIO3_13/SD1_D3/LCD_D14/CTIMER_INP1/FC10_SSELN2, label: 'J45[19]/M2_SD1_DATA3'}
- {pin_num: D9, pin_signal: PIO3_14/SD1_WR_PRT/LCD_D15/CTIMER3_MAT0/SD1_DS/FC10_SSELN3/CMP0_E, label: 'J47[9]/CMP0_E'}
- {pin_num: B6, pin_signal: PIO3_18/SD1_D7/LCD_D19/CTIMER4_MAT0/FC5_CTS_SDA_SSEL0, label: 'J44[22]/LCM_LPTE'}
- {pin_num: C6, pin_signal: PIO3_19/SD1_CARD_DET_N/LCD_D20/CTIMER4_MAT1/MCLK, label: 'U44[6]/LCM_CTP_INT_1V8', identifier: LCM_CTP_INT}
- {pin_num: D6, pin_signal: PIO3_20/SD1_RESET_N/LCD_D21/CTIMER4_MAT2, label: 'J45[23]/M2_SD1_RST_B'}
- {pin_num: R16, pin_signal: PIO3_25/FC6_SCK, label: 'J45[8]/M2_FC6_I2S_BCLK'}
- {pin_num: T16, pin_signal: PIO3_26/FC6_TXD_SCL_MISO_WS, label: 'J45[10]/M2_FC6_I2S_WS'}
- {pin_num: N14, pin_signal: PIO3_27/FC6_RXD_SDA_MOSI_DATA, label: 'J45[14]M2_FC6_I2S_D_OUT'}
- {pin_num: N15, pin_signal: PIO4_0/FC7_SCK/FREQME_GPIO_CLK/CLKOUT, label: 'U117[B2]'}
- {pin_num: M15, pin_signal: PIO4_1/FC7_TXD_SCL_MISO_WS/CLKIN, label: 'J47[5]'}
- {pin_num: M14, pin_signal: PIO4_3/FC7_CTS_SDA_SSEL0, label: 'J47[7]'}
- {pin_num: P17, pin_signal: PIO4_4/FC7_RTS_SCL_SSEL1/FC1_SCK, label: 'U44[3]/LCM_CTP_RST_1V8', identifier: LCM_CTP_RST_B}
- {pin_num: M17, pin_signal: PIO4_2/FC7_RXD_SDA_MOSI_DATA, label: 'J45[12]/M2_FC7_I2S_D_IN'}
- {pin_num: P15, pin_signal: PIO4_6/FC7_SSEL3/FC1_RXD_SDA_MOSI_DATA, label: 'J47[6]'}
- {pin_num: P16, pin_signal: PIO4_5/FC7_SSEL2/FC1_TXD_SCL_MISO_WS, label: 'U24[13]'}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_gpio.h"
#include "fsl_iopctl.h"
#include "fsl_inputmux.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
    BOARD_InitDEBUG_UARTPins();
    BOARD_InitDMICPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: cm33, enableClock: 'true'}
- pin_list:
  - {pin_num: K4, peripheral: FLEXCOMM15, signal: SCL, pin_signal: PMIC_I2C_SCL, pupdena: disabled, pupdsel: pullDown, ibena: enabled, odena: enabled}
  - {pin_num: K6, peripheral: FLEXCOMM15, signal: SDA, pin_signal: PMIC_I2C_SDA, pupdena: disabled, pupdsel: pullDown, ibena: enabled, odena: enabled}
  - {peripheral: FUSIONF1, signal: 'DSP_INTERRUPT, 1', pin_signal: MU_B}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M33 */
void BOARD_InitPins(void)
{
    /* Enables the clock for the Input Mux */
    CLOCK_EnableClock(kCLOCK_InputMux);
    /* MUB interrupt signal is selected for DSP interrupt input 1 */
    INPUTMUX_AttachSignal(INPUTMUX, 1U, kINPUTMUX_MuBToDspInterrupt);

    const uint32_t fc15_i2c_scl_config = (/* Pin is configured as I2C_SCL */
                                          IOPCTL_PIO_FUNC0 |
                                          /* Disable pull-up / pull-down function */
                                          IOPCTL_PIO_PUPD_DI |
                                          /* Enable pull-down function */
                                          IOPCTL_PIO_PULLDOWN_EN |
                                          /* Enables input buffer function */
                                          IOPCTL_PIO_INBUF_EN |
                                          /* Normal mode */
                                          IOPCTL_PIO_SLEW_RATE_NORMAL |
                                          /* Normal drive */
                                          IOPCTL_PIO_FULLDRIVE_DI |
                                          /* Analog mux is disabled */
                                          IOPCTL_PIO_ANAMUX_DI |
                                          /* Pseudo Output Drain is enabled */
                                          IOPCTL_PIO_PSEDRAIN_EN |
                                          /* Input function is not inverted */
                                          IOPCTL_PIO_INV_DI);
    /* FC15_SCL PIN (coords: K4) is configured as I2C SCL */
    IOPCTL->FC15_I2C_SCL = fc15_i2c_scl_config;

    const uint32_t fc15_i2c_sda_config = (/* Pin is configured as I2C_SDA */
                                          IOPCTL_PIO_FUNC0 |
                                          /* Disable pull-up / pull-down function */
                                          IOPCTL_PIO_PUPD_DI |
                                          /* Enable pull-down function */
                                          IOPCTL_PIO_PULLDOWN_EN |
                                          /* Enables input buffer function */
                                          IOPCTL_PIO_INBUF_EN |
                                          /* Normal mode */
                                          IOPCTL_PIO_SLEW_RATE_NORMAL |
                                          /* Normal drive */
                                          IOPCTL_PIO_FULLDRIVE_DI |
                                          /* Analog mux is disabled */
                                          IOPCTL_PIO_ANAMUX_DI |
                                          /* Pseudo Output Drain is enabled */
                                          IOPCTL_PIO_PSEDRAIN_EN |
                                          /* Input function is not inverted */
                                          IOPCTL_PIO_INV_DI);
    /* FC15_SDA PIN (coords: K6) is configured as I2C SDA */
    IOPCTL->FC15_I2C_SDA = fc15_i2c_sda_config;
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitLEDsPins:
- options: {callFromInitBoot: 'false', prefix: BOARD_, coreID: cm33, enableClock: 'true'}
- pin_list:
  - {pin_num: A10, peripheral: GPIO, signal: 'PIO1, 0', pin_signal: PIO1_0/FC4_RTS_SCL_SSEL1/SCT0_GPI1/SCT0_OUT7/CTIMER_INP8/FC3_SSEL3, direction: OUTPUT}
  - {pin_num: B12, peripheral: GPIO, signal: 'PIO0, 14', pin_signal: PIO0_14/FC2_SCK/SCT0_GPI0/SCT0_OUT0/CTIMER2_MAT0/I2S_BRIDGE_CLK_IN/SEC_PIO0_14, direction: OUTPUT}
  - {pin_num: D8, peripheral: GPIO, signal: 'PIO3, 17', pin_signal: PIO3_17/SD1_D6/LCD_D18/CTIMER3_MAT3/FC5_RXD_SDA_MOSI_DATA, direction: OUTPUT}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitLEDsPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M33 */
void BOARD_InitLEDsPins(void)
{

    /* Enables the clock for the GPIO0 module */
    CLOCK_EnableClock(kCLOCK_HsGpio0);

    /* Enables the clock for the GPIO1 module */
    CLOCK_EnableClock(kCLOCK_HsGpio1);

    /* Enables the clock for the GPIO3 module */
    CLOCK_EnableClock(kCLOCK_HsGpio3);

    gpio_pin_config_t LED_RED_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO0_14 (pin B12)  */
    GPIO_PinInit(BOARD_LED_RED_GPIO, BOARD_LED_RED_PORT, BOARD_LED_RED_PIN, &LED_RED_config);

    gpio_pin_config_t LED_GREEN_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO1_0 (pin A10)  */
    GPIO_PinInit(BOARD_LED_GREEN_GPIO, BOARD_LED_GREEN_PORT, BOARD_LED_GREEN_PIN, &LED_GREEN_config);

    gpio_pin_config_t LED_BLUE_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO3_17 (pin D8)  */
    GPIO_PinInit(BOARD_LED_BLUE_GPIO, BOARD_LED_BLUE_PORT, BOARD_LED_BLUE_PIN, &LED_BLUE_config);

    const uint32_t LED_RED = (/* Pin is configured as PIO0_14 */
                              IOPCTL_PIO_FUNC0 |
                              /* Disable pull-up / pull-down function */
                              IOPCTL_PIO_PUPD_DI |
                              /* Enable pull-down function */
                              IOPCTL_PIO_PULLDOWN_EN |
                              /* Disable input buffer function */
                              IOPCTL_PIO_INBUF_DI |
                              /* Normal mode */
                              IOPCTL_PIO_SLEW_RATE_NORMAL |
                              /* Normal drive */
                              IOPCTL_PIO_FULLDRIVE_DI |
                              /* Analog mux is disabled */
                              IOPCTL_PIO_ANAMUX_DI |
                              /* Pseudo Output Drain is disabled */
                              IOPCTL_PIO_PSEDRAIN_DI |
                              /* Input function is not inverted */
                              IOPCTL_PIO_INV_DI);
    /* PORT0 PIN14 (coords: B12) is configured as PIO0_14 */
    IOPCTL_PinMuxSet(IOPCTL, BOARD_LED_RED_PORT, BOARD_LED_RED_PIN, LED_RED);

    const uint32_t LED_GREEN = (/* Pin is configured as PIO1_0 */
                                IOPCTL_PIO_FUNC0 |
                                /* Disable pull-up / pull-down function */
                                IOPCTL_PIO_PUPD_DI |
                                /* Enable pull-down function */
                                IOPCTL_PIO_PULLDOWN_EN |
                                /* Disable input buffer function */
                                IOPCTL_PIO_INBUF_DI |
                                /* Normal mode */
                                IOPCTL_PIO_SLEW_RATE_NORMAL |
                                /* Normal drive */
                                IOPCTL_PIO_FULLDRIVE_DI |
                                /* Analog mux is disabled */
                                IOPCTL_PIO_ANAMUX_DI |
                                /* Pseudo Output Drain is disabled */
                                IOPCTL_PIO_PSEDRAIN_DI |
                                /* Input function is not inverted */
                                IOPCTL_PIO_INV_DI);
    /* PORT1 PIN0 (coords: A10) is configured as PIO1_0 */
    IOPCTL_PinMuxSet(IOPCTL, BOARD_LED_GREEN_PORT, BOARD_LED_GREEN_PIN, LED_GREEN);

    const uint32_t LED_BLUE = (/* Pin is configured as PIO3_17 */
                               IOPCTL_PIO_FUNC0 |
                               /* Disable pull-up / pull-down function */
                               IOPCTL_PIO_PUPD_DI |
                               /* Enable pull-down function */
                               IOPCTL_PIO_PULLDOWN_EN |
                               /* Disable input buffer function */
                               IOPCTL_PIO_INBUF_DI |
                               /* Normal mode */
                               IOPCTL_PIO_SLEW_RATE_NORMAL |
                               /* Normal drive */
                               IOPCTL_PIO_FULLDRIVE_DI |
                               /* Analog mux is disabled */
                               IOPCTL_PIO_ANAMUX_DI |
                               /* Pseudo Output Drain is disabled */
                               IOPCTL_PIO_PSEDRAIN_DI |
                               /* Input function is not inverted */
                               IOPCTL_PIO_INV_DI);
    /* PORT3 PIN17 (coords: D8) is configured as PIO3_17 */
    IOPCTL_PinMuxSet(IOPCTL, BOARD_LED_BLUE_PORT, BOARD_LED_BLUE_PIN, LED_BLUE);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitBUTTONSPins:
- options: {callFromInitBoot: 'false', prefix: BOARD_, coreID: cm33, enableClock: 'true'}
- pin_list:
  - {pin_num: K16, peripheral: GPIO, signal: 'PIO0, 10', pin_signal: PIO0_10/FC1_CTS_SDA_SSEL0/SCT0_GPI7/SCT0_OUT7/CTIMER1_MAT3/FC0_SSEL2/SEC_PIO0_10, direction: INPUT,
    ibena: enabled}
  - {pin_num: C12, peripheral: GPIO, signal: 'PIO0, 25', pin_signal: PIO0_25/FC3_RTS_SCL_SSEL1/FREQME_GPIO_CLK/CTIMER_INP6/FC2_SSEL3/TRACEDATA_3/CLKIN/SEC_PIO0_25,
    direction: INPUT, ibena: enabled}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBUTTONSPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M33 */
void BOARD_InitBUTTONSPins(void)
{

    /* Enables the clock for the GPIO0 module */
    CLOCK_EnableClock(kCLOCK_HsGpio0);

    gpio_pin_config_t SW2_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO0_10 (pin K16)  */
    GPIO_PinInit(BOARD_SW2_GPIO, BOARD_SW2_PORT, BOARD_SW2_PIN, &SW2_config);

    gpio_pin_config_t SW1_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO0_25 (pin C12)  */
    GPIO_PinInit(BOARD_SW1_GPIO, BOARD_SW1_PORT, BOARD_SW1_PIN, &SW1_config);

    const uint32_t SW2 = (/* Pin is configured as PIO0_10 */
                          IOPCTL_PIO_FUNC0 |
                          /* Disable pull-up / pull-down function */
                          IOPCTL_PIO_PUPD_DI |
                          /* Enable pull-down function */
                          IOPCTL_PIO_PULLDOWN_EN |
                          /* Enables input buffer function */
                          IOPCTL_PIO_INBUF_EN |
                          /* Normal mode */
                          IOPCTL_PIO_SLEW_RATE_NORMAL |
                          /* Normal drive */
                          IOPCTL_PIO_FULLDRIVE_DI |
                          /* Analog mux is disabled */
                          IOPCTL_PIO_ANAMUX_DI |
                          /* Pseudo Output Drain is disabled */
                          IOPCTL_PIO_PSEDRAIN_DI |
                          /* Input function is not inverted */
                          IOPCTL_PIO_INV_DI);
    /* PORT0 PIN10 (coords: K16) is configured as PIO0_10 */
    IOPCTL_PinMuxSet(IOPCTL, BOARD_SW2_PORT, BOARD_SW2_PIN, SW2);

    const uint32_t SW1 = (/* Pin is configured as PIO0_25 */
                          IOPCTL_PIO_FUNC0 |
                          /* Disable pull-up / pull-down function */
                          IOPCTL_PIO_PUPD_DI |
                          /* Enable pull-down function */
                          IOPCTL_PIO_PULLDOWN_EN |
                          /* Enables input buffer function */
                          IOPCTL_PIO_INBUF_EN |
                          /* Normal mode */
                          IOPCTL_PIO_SLEW_RATE_NORMAL |
                          /* Normal drive */
                          IOPCTL_PIO_FULLDRIVE_DI |
                          /* Analog mux is disabled */
                          IOPCTL_PIO_ANAMUX_DI |
                          /* Pseudo Output Drain is disabled */
                          IOPCTL_PIO_PSEDRAIN_DI |
                          /* Input function is not inverted */
                          IOPCTL_PIO_INV_DI);
    /* PORT0 PIN25 (coords: C12) is configured as PIO0_25 */
    IOPCTL_PinMuxSet(IOPCTL, BOARD_SW1_PORT, BOARD_SW1_PIN, SW1);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitDEBUG_UARTPins:
- options: {callFromInitBoot: 'true', prefix: BOARD_, coreID: cm33, enableClock: 'true'}
- pin_list:
  - {pin_num: H16, peripheral: FLEXCOMM0, signal: RXD_SDA_MOSI_DATA, pin_signal: PIO0_2/FC0_RXD_SDA_MOSI_DATA/CTIMER0_MAT2/I2S_BRIDGE_DATA_IN/SEC_PIO0_2, ibena: enabled}
  - {pin_num: G16, peripheral: FLEXCOMM0, signal: TXD_SCL_MISO_WS, pin_signal: PIO0_1/FC0_TXD_SCL_MISO_WS/CTIMER0_MAT1/I2S_BRIDGE_WS_IN/SEC_PIO0_1}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitDEBUG_UARTPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M33 */
void BOARD_InitDEBUG_UARTPins(void)
{

    const uint32_t port0_pin1_config = (/* Pin is configured as FC0_TXD_SCL_MISO_WS */
                                        IOPCTL_PIO_FUNC1 |
                                        /* Disable pull-up / pull-down function */
                                        IOPCTL_PIO_PUPD_DI |
                                        /* Enable pull-down function */
                                        IOPCTL_PIO_PULLDOWN_EN |
                                        /* Disable input buffer function */
                                        IOPCTL_PIO_INBUF_DI |
                                        /* Normal mode */
                                        IOPCTL_PIO_SLEW_RATE_NORMAL |
                                        /* Normal drive */
                                        IOPCTL_PIO_FULLDRIVE_DI |
                                        /* Analog mux is disabled */
                                        IOPCTL_PIO_ANAMUX_DI |
                                        /* Pseudo Output Drain is disabled */
                                        IOPCTL_PIO_PSEDRAIN_DI |
                                        /* Input function is not inverted */
                                        IOPCTL_PIO_INV_DI);
    /* PORT0 PIN1 (coords: G16) is configured as FC0_TXD_SCL_MISO_WS */
    IOPCTL_PinMuxSet(IOPCTL, 0U, 1U, port0_pin1_config);

    const uint32_t port0_pin2_config = (/* Pin is configured as FC0_RXD_SDA_MOSI_DATA */
                                        IOPCTL_PIO_FUNC1 |
                                        /* Disable pull-up / pull-down function */
                                        IOPCTL_PIO_PUPD_DI |
                                        /* Enable pull-down function */
                                        IOPCTL_PIO_PULLDOWN_EN |
                                        /* Enables input buffer function */
                                        IOPCTL_PIO_INBUF_EN |
                                        /* Normal mode */
                                        IOPCTL_PIO_SLEW_RATE_NORMAL |
                                        /* Normal drive */
                                        IOPCTL_PIO_FULLDRIVE_DI |
                                        /* Analog mux is disabled */
                                        IOPCTL_PIO_ANAMUX_DI |
                                        /* Pseudo Output Drain is disabled */
                                        IOPCTL_PIO_PSEDRAIN_DI |
                                        /* Input function is not inverted */
                                        IOPCTL_PIO_INV_DI);
    /* PORT0 PIN2 (coords: H16) is configured as FC0_RXD_SDA_MOSI_DATA */
    IOPCTL_PinMuxSet(IOPCTL, 0U, 2U, port0_pin2_config);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitDMICPins:
- options: {callFromInitBoot: 'true', prefix: BOARD_, coreID: cm33, enableClock: 'true'}
- pin_list:
  - {pin_num: P2, peripheral: DMIC0, signal: 'CLK, 01', pin_signal: PIO5_4/LCD_D9/DBI_D9/PDM_CLK01, ibena: enabled}
  - {pin_num: P3, peripheral: DMIC0, signal: 'DATA, 01', pin_signal: PIO5_8/LCD_D13/DBI_D13/PDM_DATA01, ibena: enabled}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitDMICPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M33 */
void BOARD_InitDMICPins(void)
{

    const uint32_t port5_pin4_config = (/* Pin is configured as PDM_CLK01 */
                                        IOPCTL_PIO_FUNC4 |
                                        /* Disable pull-up / pull-down function */
                                        IOPCTL_PIO_PUPD_DI |
                                        /* Enable pull-down function */
                                        IOPCTL_PIO_PULLDOWN_EN |
                                        /* Enables input buffer function */
                                        IOPCTL_PIO_INBUF_EN |
                                        /* Normal mode */
                                        IOPCTL_PIO_SLEW_RATE_NORMAL |
                                        /* Normal drive */
                                        IOPCTL_PIO_FULLDRIVE_DI |
                                        /* Analog mux is disabled */
                                        IOPCTL_PIO_ANAMUX_DI |
                                        /* Pseudo Output Drain is disabled */
                                        IOPCTL_PIO_PSEDRAIN_DI |
                                        /* Input function is not inverted */
                                        IOPCTL_PIO_INV_DI);
    /* PORT5 PIN4 (coords: P2) is configured as PDM_CLK01 */
    IOPCTL_PinMuxSet(IOPCTL, 5U, 4U, port5_pin4_config);

    const uint32_t port5_pin8_config = (/* Pin is configured as PDM_DATA01 */
                                        IOPCTL_PIO_FUNC4 |
                                        /* Disable pull-up / pull-down function */
                                        IOPCTL_PIO_PUPD_DI |
                                        /* Enable pull-down function */
                                        IOPCTL_PIO_PULLDOWN_EN |
                                        /* Enables input buffer function */
                                        IOPCTL_PIO_INBUF_EN |
                                        /* Normal mode */
                                        IOPCTL_PIO_SLEW_RATE_NORMAL |
                                        /* Normal drive */
                                        IOPCTL_PIO_FULLDRIVE_DI |
                                        /* Analog mux is disabled */
                                        IOPCTL_PIO_ANAMUX_DI |
                                        /* Pseudo Output Drain is disabled */
                                        IOPCTL_PIO_PSEDRAIN_DI |
                                        /* Input function is not inverted */
                                        IOPCTL_PIO_INV_DI);
    /* PORT5 PIN8 (coords: P3) is configured as PDM_DATA01 */
    IOPCTL_PinMuxSet(IOPCTL, 5U, 8U, port5_pin8_config);
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
